CREATE TABLE saldos_fidelidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    moedas NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    version BIGINT NOT NULL DEFAULT 0,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_saldos_fidelidade_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

INSERT INTO saldos_fidelidade (usuario_id, moedas, version, data_criacao, data_atualizacao)
SELECT
    t.usuario_id,
    COALESCE(SUM(CASE WHEN t.tipo = 'RESGATE' THEN -t.moedas ELSE t.moedas END), 0) AS moedas,
    0,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM transacoes_fidelidade t
GROUP BY t.usuario_id;

