CREATE TABLE configuracoes_fidelidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    taxa_conversao NUMERIC(10, 4) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO configuracoes_fidelidade (taxa_conversao, version, data_criacao, data_atualizacao)
VALUES (0.0300, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

