-- Schema inicial do projeto.
-- Em bancos legados já existentes, o baseline automático na versão 1
-- evita a recriação dessas tabelas.

CREATE TABLE usuarios (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(150) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	senha VARCHAR(255) NOT NULL,
	perfil VARCHAR(255) NOT NULL,
	ativo BOOLEAN NOT NULL,
	consentimento_programa_fidelidade BOOLEAN NOT NULL,
	criado_em TIMESTAMP NOT NULL,
	atualizado_em TIMESTAMP NOT NULL,
	CONSTRAINT ck_usuarios_perfil
		CHECK (perfil IN ('ADMIN', 'CLIENTE', 'FUNCIONARIO', 'GERENTE', 'GERENCIA_MATRIZ'))
);

CREATE TABLE produtos (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(150) NOT NULL UNIQUE,
	descricao VARCHAR(500),
	preco NUMERIC(10, 2) NOT NULL,
	ativo BOOLEAN NOT NULL,
	data_criacao TIMESTAMP NOT NULL,
	data_atualizacao TIMESTAMP NOT NULL
);

CREATE TABLE lojas (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(150) NOT NULL,
	cnpj VARCHAR(18) NOT NULL UNIQUE,
	endereco VARCHAR(255) NOT NULL,
	ativa BOOLEAN NOT NULL,
	data_criacao TIMESTAMP NOT NULL,
	data_atualizacao TIMESTAMP NOT NULL
);

CREATE TABLE pedidos (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	loja_id BIGINT NOT NULL,
	cliente_id BIGINT NOT NULL,
	canal_pedido VARCHAR(20) NOT NULL,
	status_pedido VARCHAR(20) NOT NULL,
	valor_total NUMERIC(10, 2) NOT NULL,
	data_criacao TIMESTAMP NOT NULL,
	data_atualizacao TIMESTAMP NOT NULL,
	CONSTRAINT ck_pedidos_canal_pedido
		CHECK (canal_pedido IN ('APP', 'SITE', 'TOTEM', 'PICKUP', 'BALCAO')),
	CONSTRAINT ck_pedidos_status_pedido
		CHECK (status_pedido IN ('CRIADO', 'CONFIRMADO', 'PREPARO', 'PRONTO', 'ENTREGUE', 'CANCELADO')),
	CONSTRAINT fk_pedidos_loja
		FOREIGN KEY (loja_id) REFERENCES lojas (id),
	CONSTRAINT fk_pedidos_cliente
		FOREIGN KEY (cliente_id) REFERENCES usuarios (id)
);

CREATE TABLE pagamentos (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pedido_id BIGINT NOT NULL UNIQUE,
	forma_pagamento VARCHAR(20) NOT NULL,
	status_pagamento VARCHAR(20) NOT NULL,
	valor NUMERIC(10, 2) NOT NULL,
	codigo_transacao VARCHAR(100),
	observacao VARCHAR(500),
	data_pagamento TIMESTAMP,
	data_criacao TIMESTAMP NOT NULL,
	data_atualizacao TIMESTAMP NOT NULL,
	CONSTRAINT ck_pagamentos_forma_pagamento
		CHECK (forma_pagamento IN ('DINHEIRO', 'CARTAO_CREDITO', 'CARTAO_DEBITO', 'PIX', 'VALE_ALIMENTACAO', 'VALE_REFEICAO')),
	CONSTRAINT ck_pagamentos_status_pagamento
		CHECK (status_pagamento IN ('PENDENTE', 'APROVADO', 'RECUSADO', 'CANCELADO')),
	CONSTRAINT fk_pagamentos_pedido
		FOREIGN KEY (pedido_id) REFERENCES pedidos (id)
);

CREATE TABLE itens_pedido (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	pedido_id BIGINT NOT NULL,
	produto_id BIGINT NOT NULL,
	quantidade INTEGER NOT NULL,
	preco_unitario NUMERIC(10, 2) NOT NULL,
	subtotal NUMERIC(10, 2) NOT NULL,
	data_criacao TIMESTAMP NOT NULL,
	data_atualizacao TIMESTAMP NOT NULL,
	CONSTRAINT ck_itens_pedido_quantidade
		CHECK (quantidade >= 1),
	CONSTRAINT fk_itens_pedido_pedido
		FOREIGN KEY (pedido_id) REFERENCES pedidos (id),
	CONSTRAINT fk_itens_pedido_produto
		FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE TABLE fidelidades (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	usuario_id BIGINT NOT NULL UNIQUE,
	pontos_atuais INTEGER NOT NULL,
	pontos_totais_acumulados INTEGER NOT NULL,
	data_criacao TIMESTAMP NOT NULL,
	data_atualizacao TIMESTAMP NOT NULL,
	CONSTRAINT ck_fidelidades_pontos_atuais
		CHECK (pontos_atuais >= 0),
	CONSTRAINT ck_fidelidades_pontos_totais_acumulados
		CHECK (pontos_totais_acumulados >= 0),
	CONSTRAINT fk_fidelidades_usuario
		FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE TABLE estoques (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	loja_id BIGINT NOT NULL,
	produto_id BIGINT NOT NULL,
	quantidade INTEGER NOT NULL,
	versao BIGINT NOT NULL,
	data_criacao TIMESTAMP NOT NULL,
	data_atualizacao TIMESTAMP NOT NULL,
	CONSTRAINT uk_estoques_loja_produto UNIQUE (loja_id, produto_id),
	CONSTRAINT ck_estoques_quantidade
		CHECK (quantidade >= 0),
	CONSTRAINT fk_estoques_loja
		FOREIGN KEY (loja_id) REFERENCES lojas (id),
	CONSTRAINT fk_estoques_produto
		FOREIGN KEY (produto_id) REFERENCES produtos (id)
);

CREATE INDEX idx_pedidos_loja_id ON pedidos (loja_id);
CREATE INDEX idx_pedidos_cliente_id ON pedidos (cliente_id);
CREATE INDEX idx_itens_pedido_pedido_id ON itens_pedido (pedido_id);
CREATE INDEX idx_itens_pedido_produto_id ON itens_pedido (produto_id);
CREATE INDEX idx_pagamentos_pedido_id ON pagamentos (pedido_id);
CREATE INDEX idx_fidelidades_usuario_id ON fidelidades (usuario_id);
CREATE INDEX idx_estoques_loja_id ON estoques (loja_id);
CREATE INDEX idx_estoques_produto_id ON estoques (produto_id);

