CREATE TABLE movimentacoes_estoque (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estoque_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    quantidade INTEGER NOT NULL,
    motivo VARCHAR(500),
    usuario_id BIGINT NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    CONSTRAINT ck_movimentacoes_estoque_tipo
        CHECK (tipo IN ('ENTRADA', 'SAIDA', 'AJUSTE')),
    CONSTRAINT ck_movimentacoes_estoque_quantidade
        CHECK (quantidade > 0),
    CONSTRAINT fk_movimentacoes_estoque_estoque
        FOREIGN KEY (estoque_id) REFERENCES estoques (id),
    CONSTRAINT fk_movimentacoes_estoque_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_movimentacoes_estoque_estoque_id ON movimentacoes_estoque (estoque_id);
CREATE INDEX idx_movimentacoes_estoque_usuario_id ON movimentacoes_estoque (usuario_id);
CREATE INDEX idx_movimentacoes_estoque_data_criacao ON movimentacoes_estoque (data_criacao);

