CREATE TABLE request_execution_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(150) NOT NULL,
    usuario_id BIGINT NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    response_body TEXT NOT NULL,
    status_code INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_request_execution_key_user UNIQUE (idempotency_key, usuario_id),
    CONSTRAINT fk_request_execution_user
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX idx_request_execution_key ON request_execution_records (idempotency_key);
CREATE INDEX idx_request_execution_user ON request_execution_records (usuario_id);
CREATE INDEX idx_request_execution_created_at ON request_execution_records (created_at);

