CREATE TABLE transacoes_fidelidade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    pedido_id BIGINT,
    tipo VARCHAR(20) NOT NULL,
    moedas NUMERIC(10, 2) NOT NULL,
    data_criacao TIMESTAMP NOT NULL,
    CONSTRAINT ck_transacoes_fidelidade_tipo
        CHECK (tipo IN ('GANHO', 'RESGATE', 'ESTORNO')),
    CONSTRAINT ck_transacoes_fidelidade_moedas
        CHECK (moedas >= 0),
    CONSTRAINT fk_transacoes_fidelidade_usuario
        FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_transacoes_fidelidade_pedido
        FOREIGN KEY (pedido_id) REFERENCES pedidos (id),
    CONSTRAINT uq_transacoes_fidelidade_pedido_tipo
        UNIQUE (pedido_id, tipo)
);

CREATE INDEX idx_transacoes_fidelidade_usuario_id ON transacoes_fidelidade (usuario_id);
CREATE INDEX idx_transacoes_fidelidade_pedido_id ON transacoes_fidelidade (pedido_id);

